#!/usr/bin/env node
/*
 * PDFLokal — scripts/gen-riwayat.js  (THE WORK LOG)
 * ============================================================================
 * Reads `git log` and rewrites ONE region of dukung.html, between
 *   <!-- riwayat:start -->  and  <!-- riwayat:end -->
 * Run it with `npm run riwayat`.
 *
 * WHAT IT IS, in his words (2026-08-28):
 *   "put it somewhere bentuknya slider aja... commit historynya by timeline.
 *    from most recent. intinya cuma perlu ngasih tau, kapan dan ngapain...
 *    nanti scrollnya bakal banyak ke bawah terus dan itu yang bakal showing
 *    not telling"
 *
 *   So: NOT a page, NOT a chart, NOT a summary. One scrollable column of every
 *   change ever made, newest first, date and what. **The length is the
 *   argument.** A reader scrolls, keeps scrolling, and concludes on their own
 *   that someone actually works on this. Any total, average or "N commits"
 *   headline would be TELLING, and would let them stop scrolling — which is the
 *   one thing this element cannot afford.
 *
 * WHY STATIC HTML, COMMITTED, not fetched at runtime:
 *   Same doctrine as gen-seo-pages.js. Nothing is transformed at deploy time.
 *   If this script is never run again the log still renders, just stale — a
 *   failure the reader can see (the top date stops moving) rather than an empty
 *   box. It is a trust element; a trust element that renders empty when a fetch
 *   fails has done the opposite of its job.
 *
 * ⛔ NO TIME OF DAY. His ruling, same day: "jangan kasih tau jam juga". Dates
 *   only. `%cd` is formatted to a date and the hour is never read.
 * ⛔ NO TRANSLATION of commit subjects. They are English dev-speak, and a
 *   machine paraphrase of ~500 of them is ~500 chances to say something false
 *   about work that really happened. What a non-developer needs here is the
 *   WHEN and the sheer count of rows; the KIND tag carries the rest.
 * ========================================================================== */

import { readFileSync, writeFileSync } from 'node:fs';
import { execFileSync } from 'node:child_process';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const PAGE = join(ROOT, 'dukung.html');
const START = '<!-- riwayat:start -->';
const END = '<!-- riwayat:end -->';

const BULAN = ['Januari', 'Februari', 'Maret', 'April', 'Mei', 'Juni',
  'Juli', 'Agustus', 'September', 'Oktober', 'November', 'Desember'];

/* The conventional-commit prefix, said in Indonesian. Anything without a prefix
   (the early months predate the convention) gets NO tag rather than a guessed
   one — an invented label on real work is worse than a missing one. */
const JENIS = {
  feat: 'Fitur',
  fix: 'Perbaikan',
  perf: 'Kecepatan',
  copy: 'Tulisan',
  style: 'Tampilan',
  redesign: 'Tampilan',
  polish: 'Tampilan',
  refactor: 'Rapi-rapi',
  test: 'Tes',
  docs: 'Catatan',
  chore: 'Teknis',
  build: 'Teknis',
  ci: 'Teknis',
  rail: 'Teknis',
};

/* ---- ENTRIES HE STRUCK ----
   This log is generated from git, so an entry cannot be deleted by editing the
   page: the next `npm run riwayat` would put it straight back. A subject listed
   here is hidden from the PUBLIC log only. Nothing is rewritten in git, and the
   commit stays reachable on GitHub, which the page links to.
   Add to this list ONLY when Fauzan strikes a specific line. Do not use it to
   tidy the log — the volume is the whole argument, and quietly pruning it is
   the one thing this element cannot do honestly. */
const DISEMBUNYIKAN = [
  // Struck 2026-08-28. Self-referential: a commit about putting his own face
  // and name on the site, reading back to a stranger as a line about "his face,
  // his name".
  'the product speaks as one person now: his face, his name, saya not kami',
];

const esc = (s) => s.replace(/&/g, '&amp;').replace(/</g, '&lt;')
  .replace(/>/g, '&gt;').replace(/"/g, '&quot;');

/* %cd formatted to a DATE. The hour is deliberately never in this string. */
const commits = execFileSync('git',
  ['-C', ROOT, 'log', '--no-merges', '--format=%cd\t%s', '--date=format:%Y-%m-%d'],
  { encoding: 'utf8', maxBuffer: 32 * 1024 * 1024 })
  .trim().split('\n')
  .map((l) => {
    const i = l.indexOf('\t');
    return { tanggal: l.slice(0, i), subject: l.slice(i + 1) };
  })
  .filter((c) => !DISEMBUNYIKAN.includes(c.subject));

const tanggalPanjang = (iso) => {
  const [y, m, d] = iso.split('-');
  return `${+d} ${BULAN[+m - 1]} ${y}`;
};

const rows = commits.map((c) => {
  const m = /^([a-z]+)(\(.+?\))?:\s*(.+)$/.exec(c.subject);
  const jenis = m && JENIS[m[1]] ? JENIS[m[1]] : null;
  const teks = m && JENIS[m[1]] ? m[3] : c.subject;
  const tag = jenis ? `<b class="rw-jenis">${jenis}</b>` : '';
  return `      <li><time datetime="${c.tanggal}">${tanggalPanjang(c.tanggal)}</time>${tag}<span>${esc(teks)}</span></li>`;
}).join('\n');

const blok = `${START}
      <!-- ⚠️ GENERATED by scripts/gen-riwayat.js (npm run riwayat). Everything
           between these two markers is derived from git log and WILL BE
           OVERWRITTEN. Copy lives outside the markers.
           No totals here, and no time of day, both on his ruling. See the
           script header. -->
      <ol class="rw-log" tabindex="0" aria-label="Daftar semua perubahan PDFLokal, dari yang paling baru">
${rows}
      </ol>
      ${END}`;

const html = readFileSync(PAGE, 'utf8');
const a = html.indexOf(START);
const b = html.indexOf(END);
if (a === -1 || b === -1) {
  console.error(`  ✖ ${PAGE} has no ${START} / ${END} markers. Nothing written.`);
  process.exit(1);
}
writeFileSync(PAGE, html.slice(0, a) + blok + html.slice(b + END.length));

console.log(`
  ✓ dukung.html work log updated — ${commits.length} rows, newest ${commits[0].tanggal}
`);
